name: Release

on:
  push:
    paths:
      - "action.yml"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # <- Suggested to get all tags
          token: ${{ secrets.GH_TOKEN }} # <- This is required

      - name: Release
        uses: mbround18/auto@v1.5.0
        with:
          token: ${{ secrets.GH_TOKEN }}
